### ISSUE TITLE
Mojave support 

### ISSUE THREAD

**Issue by mrpigeonn** [lov/QLVJ#1]
Hello, 

Apparently QLVJ doesn't work on Mojave.
Is there anyone experiencing this ?

I hav a mid 2012 15 Inch mac

Regards

**Comment by ghost** [comment]
Hi there, not sure if the developer sees this but we really would like this for Bigsur or monterey, its a travesty that we cannot preview HAP on OSX

**Comment by lov** [comment]
The Quicktime framework is no longer exists on newer system because it was 32bit only - in other words, there is no way to make this working on modern, 64 bit system. 

Check out https://github.com/Marginal/QLVideo/

**Comment by ghost** [comment]
I understand that this Ql plugin wont work but it is a shame that no other kind of utility can be created for quicklook using the existing architecture

**Comment by lov** [comment]
Not sure why you think there is no other tool - I just mentioned one for you in my previous reply. 😉

**Comment by ghost** [comment]
The QL video link? what puzzles me is that Adobe Bridge has no problem showing the previews. Im wondering if there would be some way to adapt that,

**Comment by ghost** [comment]
Hey Lov, that doesn't seem to work for me to preview HAP on OSX 11.6.4

**Comment by lov** [comment]
Yeah, Adobe Bridge is a 3rd party app, that is a very different case than adding support for Apple's Quicklook via the official API Apple provides. Honestly, I don't have experience with QLVideo but it is listed on the official [HAP website](https://hap.video/integrations.html) so I guess it should work.

Letting the guys know there on Github is your best bet - I'm sure someone will help you out there.
